### ISSUE TITLE
Automated builds

### ISSUE THREAD

**Issue by pgporada** [FEMR/femr#400]
Have you considered using [Travis CI](https://travis-ci.org/) to automatically build your scala/play code to show that it is compiling correctly when commits get merged?

**Comment by kevinzurek** [comment]
Set up automatic building (only compiling, not testing) and added the README image to track the master branch. We will update this to also run tests after finalizing the unit testing framework. Thanks for the idea, Phil!

Going to close this issue here and move it to JIRA:
https://teamfemr.atlassian.net/browse/FEMR-34
